---
name: test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  lint:
    name: RuboCop
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true
    - name: Run RuboCop
      run: bundle exec rubocop
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
        gemfile:
          - gemfiles/activerecord_5.2.gemfile
          - gemfiles/activerecord_6.0.gemfile
          - gemfiles/activerecord_6.1.gemfile
        experimental: [false]
        include:
          - ruby: 2.3
            gemfile: gemfiles/activerecord_5.2.gemfile
            experimental: false
          - ruby: 2.4
            gemfile: gemfiles/activerecord_5.2.gemfile
            experimental: false
          - ruby: "ruby-head"
            experimental: true
          - ruby: "truffleruby-head"
            experimental: true
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec
